# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Api.QualitySafetyObservationsProjectObservationTemplates do
  @moduledoc """
  API calls for all endpoints tagged `QualitySafetyObservationsProjectObservationTemplates`.
  """

  alias Procore.Connection
  import Procore.RequestBuilder

  @doc """
  Bulk Update Project Observation Templates
  Updates multiple Project Observation Templates

  ### Parameters

  - `connection` (Procore.Connection): Connection to server
  - `procore_company_id` (integer()): Unique company identifier associated with the Procore User Account.
  - `project_id` (integer()): Unique identifier for the project.
  - `rest_v10_projects_project_id_observation_templates_bulk_update_patch_request` (RestV10ProjectsProjectIdObservationTemplatesBulkUpdatePatchRequest): 
  - `opts` (keyword): Optional parameters
    - `:observation_template_ids` ([integer()]): IDs of all Project Observation Templates specified for bulk update

  ### Returns

  - `{:ok, [%ProjectObservationTemplate1{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec rest_v10_projects_project_id_observation_templates_bulk_update_patch(
          Tesla.Env.client(),
          integer(),
          integer(),
          Procore.Model.RestV10ProjectsProjectIdObservationTemplatesBulkUpdatePatchRequest.t(),
          keyword()
        ) ::
          {:ok, Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet401Response.t()}
          | {:ok, [Procore.Model.ProjectObservationTemplate1.t()]}
          | {:error, Tesla.Env.t()}
  def rest_v10_projects_project_id_observation_templates_bulk_update_patch(
        connection,
        procore_company_id,
        project_id,
        rest_v10_projects_project_id_observation_templates_bulk_update_patch_request,
        opts \\ []
      ) do
    optional_params = %{
      :observation_template_ids => :query
    }

    request =
      %{}
      |> method(:patch)
      |> url("/rest/v1.0/projects/#{project_id}/observation_templates/bulk_update")
      |> add_param(:headers, :"Procore-Company-Id", procore_company_id)
      |> add_param(
        :body,
        :body,
        rest_v10_projects_project_id_observation_templates_bulk_update_patch_request
      )
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Procore.Model.ProjectObservationTemplate1},
      {400, Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet401Response},
      {401, Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet401Response},
      {403, Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet401Response},
      {404, Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet401Response},
      {422, Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet401Response}
    ])
  end
end
