# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :amount,
    :company,
    :cost_code,
    :created_at,
    :description,
    :extended_type,
    :holder,
    :line_item_type,
    :origin_data,
    :origin_id,
    :position,
    :project,
    :quantity,
    :tax_code_id,
    :total_amount,
    :extended_amount,
    :unit_cost,
    :uom,
    :updated_at,
    :change_event_line_item,
    :errors
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :amount => String.t() | nil,
          :company =>
            Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCompany.t() | nil,
          :cost_code =>
            Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCostCode.t() | nil,
          :created_at => DateTime.t() | nil,
          :description => String.t() | nil,
          :extended_type => String.t() | nil,
          :holder =>
            Procore.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInnerAllOfHolder.t() | nil,
          :line_item_type => Procore.Model.LineItemType.t() | nil,
          :origin_data => String.t() | nil,
          :origin_id => String.t() | nil,
          :position => integer() | nil,
          :project => Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerProject.t() | nil,
          :quantity => String.t() | nil,
          :tax_code_id => integer() | nil,
          :total_amount => String.t() | nil,
          :extended_amount => String.t() | nil,
          :unit_cost => String.t() | nil,
          :uom => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :change_event_line_item =>
            Procore.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseEntitiesInnerChangeEventLineItem.t()
            | nil,
          :errors =>
            Procore.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors.t()
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :company,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCompany
    )
    |> Deserializer.deserialize(
      :cost_code,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCostCode
    )
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(
      :holder,
      :struct,
      Procore.Model.ArrayOfPotentialChangeOrderLineItemsErrorsInnerAllOfHolder
    )
    |> Deserializer.deserialize(:line_item_type, :struct, Procore.Model.LineItemType)
    |> Deserializer.deserialize(
      :project,
      :struct,
      Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerProject
    )
    |> Deserializer.deserialize(:updated_at, :datetime, nil)
    |> Deserializer.deserialize(
      :change_event_line_item,
      :struct,
      Procore.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseEntitiesInnerChangeEventLineItem
    )
    |> Deserializer.deserialize(
      :errors,
      :struct,
      Procore.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors
    )
  end
end
