# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.BidLinks do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :uploads,
    :cost_codes,
    :bid_pdf
  ]

  @type t :: %__MODULE__{
          :uploads => String.t() | nil,
          :cost_codes => String.t() | nil,
          :bid_pdf => String.t() | nil
        }

  def decode(value) do
    value
  end
end
