# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.BimFileUploadCreatedBy do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :company_name,
    :name,
    :locale,
    :login
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :company_name => String.t() | nil,
          :name => String.t() | nil,
          :locale => String.t() | nil,
          :login => String.t() | nil
        }

  def decode(value) do
    value
  end
end
