# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.BimPlanBatchCreateResponseErrorsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :bim_level_id,
    :drawing_id,
    :upload_uuid,
    :sheet_map_start,
    :sheet_map_end,
    :model_map_start,
    :model_map_end,
    :errors
  ]

  @type t :: %__MODULE__{
          :bim_level_id => integer(),
          :drawing_id => integer() | nil,
          :upload_uuid => String.t() | nil,
          :sheet_map_start => Procore.Model.Body120BimPlanOneOfSheetMapStart.t() | nil,
          :sheet_map_end => Procore.Model.Body120BimPlanOneOfSheetMapStart.t() | nil,
          :model_map_start => Procore.Model.Body120BimPlanOneOfModelMapStart.t() | nil,
          :model_map_end => Procore.Model.Body120BimPlanOneOfModelMapStart.t() | nil,
          :errors =>
            Procore.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors.t()
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :sheet_map_start,
      :struct,
      Procore.Model.Body120BimPlanOneOfSheetMapStart
    )
    |> Deserializer.deserialize(
      :sheet_map_end,
      :struct,
      Procore.Model.Body120BimPlanOneOfSheetMapStart
    )
    |> Deserializer.deserialize(
      :model_map_start,
      :struct,
      Procore.Model.Body120BimPlanOneOfModelMapStart
    )
    |> Deserializer.deserialize(
      :model_map_end,
      :struct,
      Procore.Model.Body120BimPlanOneOfModelMapStart
    )
    |> Deserializer.deserialize(
      :errors,
      :struct,
      Procore.Model.RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors
    )
  end
end
