# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body59BimViewFolder do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :path,
    :bim_file_id
  ]

  @type t :: %__MODULE__{
          :path => [String.t()],
          :bim_file_id => integer()
        }

  def decode(value) do
    value
  end
end
