# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body121 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :view,
    :bim_plan
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :view => String.t() | nil,
          :bim_plan => Procore.Model.Body121BimPlan.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:bim_plan, :struct, Procore.Model.Body121BimPlan)
  end
end
