# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body145 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :title,
    :base_bid,
    :alternates
  ]

  @type t :: %__MODULE__{
          :title => String.t(),
          :base_bid => [Procore.Model.Body145BaseBidInner.t()] | nil,
          :alternates => [Procore.Model.Body145AlternatesInner.t()] | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:base_bid, :list, Procore.Model.Body145BaseBidInner)
    |> Deserializer.deserialize(:alternates, :list, Procore.Model.Body145AlternatesInner)
  end
end
