# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body95 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :attachments,
    :item
  ]

  @type t :: %__MODULE__{
          :attachments => [String.t()] | nil,
          :item => Procore.Model.DirectCostItem2.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:item, :struct, Procore.Model.DirectCostItem2)
  end
end
