# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body28 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :updates
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :updates => [Procore.Model.PurchaseOrderContract1.t()]
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:updates, :list, Procore.Model.PurchaseOrderContract1)
  end
end
