# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body134 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :bim_model_revision
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :bim_model_revision => Procore.Model.Body134BimModelRevision.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :bim_model_revision,
      :struct,
      Procore.Model.Body134BimModelRevision
    )
  end
end
