# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body144BaseBidInnerBidFormItemsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :cost_code_id,
    :description,
    :position,
    :subject,
    :item_type,
    :response_type
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :cost_code_id => integer() | nil,
          :description => String.t() | nil,
          :position => integer() | nil,
          :subject => String.t() | nil,
          :item_type => String.t() | nil,
          :response_type => String.t() | nil
        }

  def decode(value) do
    value
  end
end
