# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body88Markup do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :applies_to_all,
    :compound,
    :markup_conditions,
    :markup_set,
    :name,
    :percentage,
    :position,
    :prime_line_item_id,
    :wbs_code_id
  ]

  @type t :: %__MODULE__{
          :applies_to_all => boolean() | nil,
          :compound => Procore.Model.FinancialMarkupCompound.t() | nil,
          :markup_conditions => [Procore.Model.Body88MarkupMarkupConditionsInner.t()] | nil,
          :markup_set => String.t(),
          :name => String.t(),
          :percentage => String.t(),
          :position => integer() | nil,
          :prime_line_item_id => integer() | nil,
          :wbs_code_id => integer() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:compound, :struct, Procore.Model.FinancialMarkupCompound)
    |> Deserializer.deserialize(
      :markup_conditions,
      :list,
      Procore.Model.Body88MarkupMarkupConditionsInner
    )
  end
end
