# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body146 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :billing_period
  ]

  @type t :: %__MODULE__{
          :billing_period => Procore.Model.BillingPeriod1.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:billing_period, :struct, Procore.Model.BillingPeriod1)
  end
end
