# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body40 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :document_id,
    :document_custom_tag
  ]

  @type t :: %__MODULE__{
          :document_id => integer(),
          :document_custom_tag => Procore.Model.CustomTag.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:document_custom_tag, :struct, Procore.Model.CustomTag)
  end
end
