# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body103 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :deletes
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :deletes => [Procore.Model.Body103DeletesInner.t()]
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:deletes, :list, Procore.Model.Body103DeletesInner)
  end
end
