# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body102 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :sub_job_id,
    :standard_cost_code_list_id
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :sub_job_id => integer() | nil,
          :standard_cost_code_list_id => integer()
        }

  def decode(value) do
    value
  end
end
