# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body134 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :view,
    :bim_levels
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :view => String.t() | nil,
          :bim_levels => [Procore.Model.Body132BimLevel.t()]
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:bim_levels, :list, Procore.Model.Body132BimLevel)
  end
end
