# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Body119 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :project_id,
    :bim_view_folder
  ]

  @type t :: %__MODULE__{
          :project_id => integer(),
          :bim_view_folder => Procore.Model.Body119BimViewFolder.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:bim_view_folder, :struct, Procore.Model.Body119BimViewFolder)
  end
end
