# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.BudgetDetailFilterOptions do
  @moduledoc """
  Budget Detail Filters Object
  """

  @derive Jason.Encoder
  defstruct [
    :biller,
    :cost_code,
    :root_cost_code,
    :cost_type,
    :vendor,
    :detail_type
  ]

  @type t :: %__MODULE__{
          :biller => [Procore.Model.BudgetDetailFilterOptionsBillerInner.t()] | nil,
          :cost_code => [integer()] | nil,
          :root_cost_code => [integer()] | nil,
          :cost_type => [integer()] | nil,
          :vendor => [integer()] | nil,
          :detail_type => [String.t()] | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :biller,
      :list,
      Procore.Model.BudgetDetailFilterOptionsBillerInner
    )
  end
end
