# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.BulkCreateProjectMembershipBody do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :party_ids
  ]

  @type t :: %__MODULE__{
          :party_ids => [integer()]
        }

  def decode(value) do
    value
  end
end
