# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.BusinessNormalViewClassificationsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :abbreviation,
    :key,
    :name
  ]

  @type t :: %__MODULE__{
          :abbreviation => String.t() | nil,
          :key => String.t() | nil,
          :name => String.t() | nil
        }

  def decode(value) do
    value
  end
end
