# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ChecklistSignatureCreateBody1 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :attachment_id
  ]

  @type t :: %__MODULE__{
          :attachment_id => integer()
        }

  def decode(value) do
    value
  end
end
