# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ChecklistListGroupedDataPermissions do
  @moduledoc """
  User permissions for the specific Inspection
  """

  @derive Jason.Encoder
  defstruct [
    :can_edit
  ]

  @type t :: %__MODULE__{
          :can_edit => boolean() | nil
        }

  def decode(value) do
    value
  end
end
