# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.CompanyPersonBody do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :person
  ]

  @type t :: %__MODULE__{
          :person => Procore.Model.CompanyPerson1.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:person, :struct, Procore.Model.CompanyPerson1)
  end
end
