# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ConfigurableFieldSetFields do
  @moduledoc """
  Specifies the hash of fields on an object. This is for example purposes only.
  """

  @derive Jason.Encoder
  defstruct [
    :field_1,
    :custom_field_1
  ]

  @type t :: %__MODULE__{
          :field_1 => Procore.Model.ConfigurableFieldSetFieldsField1.t() | nil,
          :custom_field_1 => Procore.Model.ConfigurableFieldSetFieldsCustomField1.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:field_1, :struct, Procore.Model.ConfigurableFieldSetFieldsField1)
    |> Deserializer.deserialize(
      :custom_field_1,
      :struct,
      Procore.Model.ConfigurableFieldSetFieldsCustomField1
    )
  end
end
