# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Default do
  @moduledoc """
  Line Item (when the 'default' view is requested)
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :amount,
    :company,
    :cost_code,
    :created_at,
    :description,
    :extended_type,
    :holder,
    :line_item_type,
    :origin_data,
    :origin_id,
    :position,
    :project,
    :quantity,
    :tax_code_id,
    :total_amount,
    :extended_amount,
    :unit_cost,
    :uom,
    :wbs_code,
    :updated_at,
    :change_event_line_item,
    :currency_configuration
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :amount => String.t() | nil,
          :company =>
            Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCompany.t() | nil,
          :cost_code => Procore.Model.Extended.t() | nil,
          :created_at => DateTime.t() | nil,
          :description => String.t() | nil,
          :extended_type => String.t() | nil,
          :holder =>
            Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerHolder.t() | nil,
          :line_item_type => Procore.Model.LineItemType.t() | nil,
          :origin_data => String.t() | nil,
          :origin_id => String.t() | nil,
          :position => integer() | nil,
          :project =>
            Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerAllOfProject.t() | nil,
          :quantity => String.t() | nil,
          :tax_code_id => integer() | nil,
          :total_amount => String.t() | nil,
          :extended_amount => String.t() | nil,
          :unit_cost => String.t() | nil,
          :uom => String.t() | nil,
          :wbs_code =>
            Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerWbsCode.t() | nil,
          :updated_at => DateTime.t() | nil,
          :change_event_line_item => Procore.Model.DefaultChangeEventLineItem.t() | nil,
          :currency_configuration =>
            Procore.Model.RestV10WorkOrderContractsSyncPatch200ResponseEntitiesInnerAllOfCurrencyConfiguration.t()
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :company,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerCompany
    )
    |> Deserializer.deserialize(:cost_code, :struct, Procore.Model.Extended)
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(
      :holder,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerHolder
    )
    |> Deserializer.deserialize(:line_item_type, :struct, Procore.Model.LineItemType)
    |> Deserializer.deserialize(
      :project,
      :struct,
      Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerAllOfProject
    )
    |> Deserializer.deserialize(
      :wbs_code,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerWbsCode
    )
    |> Deserializer.deserialize(:updated_at, :datetime, nil)
    |> Deserializer.deserialize(
      :change_event_line_item,
      :struct,
      Procore.Model.DefaultChangeEventLineItem
    )
    |> Deserializer.deserialize(
      :currency_configuration,
      :struct,
      Procore.Model.RestV10WorkOrderContractsSyncPatch200ResponseEntitiesInnerAllOfCurrencyConfiguration
    )
  end
end
