# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ErrorsResponseFields do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :label
  ]

  @type t :: %__MODULE__{
          :label => String.t() | nil
        }

  def decode(value) do
    value
  end
end
