# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Extended3ChangeEventsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :number
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :number => String.t() | nil
        }

  def decode(value) do
    value
  end
end
