# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.FinancialMarkupMarkupConditionsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :match_type,
    :wbs_segment_id,
    :markup_condition_items
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :match_type => String.t() | nil,
          :wbs_segment_id => integer() | nil,
          :markup_condition_items =>
            [Procore.Model.FinancialMarkupMarkupConditionsInnerMarkupConditionItemsInner.t()]
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :markup_condition_items,
      :list,
      Procore.Model.FinancialMarkupMarkupConditionsInnerMarkupConditionItemsInner
    )
  end
end
