# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ImageCategoryLinks do
  @moduledoc """
  Action links
  """

  @derive Jason.Encoder
  defstruct [
    :show,
    :delete,
    :update
  ]

  @type t :: %__MODULE__{
          :show => String.t() | nil,
          :delete => String.t() | nil,
          :update => String.t() | nil
        }

  def decode(value) do
    value
  end
end
