# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Lookahead do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :start_date,
    :end_date,
    :copied_from_id
  ]

  @type t :: %__MODULE__{
          :start_date => String.t(),
          :end_date => String.t(),
          :copied_from_id => integer() | nil
        }

  def decode(value) do
    value
  end
end
