# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ManualHold do
  @moduledoc """
  Manual hold for an invoice
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :status,
    :description,
    :created_by,
    :created_at,
    :updated_by,
    :updated_at,
    :company_id,
    :project_id,
    :invoice_id,
    :hold_type,
    :vendor_id,
    :visible_to_vendor,
    :attachments
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :status => String.t() | nil,
          :description => String.t() | nil,
          :created_by => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :updated_by => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :company_id => integer() | nil,
          :project_id => integer() | nil,
          :invoice_id => integer() | nil,
          :hold_type => String.t() | nil,
          :vendor_id => integer() | nil,
          :visible_to_vendor => boolean() | nil,
          :attachments =>
            [Procore.Model.RestV11RequisitionsGet200ResponseInnerAttachmentsInner.t()] | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(:updated_at, :datetime, nil)
    |> Deserializer.deserialize(
      :attachments,
      :list,
      Procore.Model.RestV11RequisitionsGet200ResponseInnerAttachmentsInner
    )
  end
end
