# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.MaterialBody do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :material
  ]

  @type t :: %__MODULE__{
          :material => Procore.Model.MaterialProperties.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:material, :struct, Procore.Model.MaterialProperties)
  end
end
