# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.OriginPayload1 do
  @moduledoc """
  Payload Keys change depending on origin.
  """

  @derive Jason.Encoder
  defstruct [
    :checklist_item_id,
    :checklist_list_id,
    :coordination_issue_id,
    :coordination_issue_number,
    :incident_action_id,
    :incident_id,
    :bim_model_id,
    :bim_model_name
  ]

  @type t :: %__MODULE__{
          :checklist_item_id => integer() | nil,
          :checklist_list_id => integer() | nil,
          :coordination_issue_id => integer() | nil,
          :coordination_issue_number => integer() | nil,
          :incident_action_id => integer() | nil,
          :incident_id => integer() | nil,
          :bim_model_id => integer() | nil,
          :bim_model_name => String.t() | nil
        }

  def decode(value) do
    value
  end
end
