# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.Project6 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :address,
    :stage_name,
    :status_name,
    :type_name,
    :open_items,
    :created_by
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :address => Procore.Model.Project6Address.t() | nil,
          :stage_name => String.t() | nil,
          :status_name => String.t() | nil,
          :type_name => String.t() | nil,
          :open_items => [Procore.Model.Project6OpenItemsInner.t()] | nil,
          :created_by => Procore.Model.Project6CreatedBy.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:address, :struct, Procore.Model.Project6Address)
    |> Deserializer.deserialize(:open_items, :list, Procore.Model.Project6OpenItemsInner)
    |> Deserializer.deserialize(:created_by, :struct, Procore.Model.Project6CreatedBy)
  end
end
