# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ProjectObservationType2 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :category,
    :active
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :category => String.t() | nil,
          :active => boolean() | nil
        }

  def decode(value) do
    value
  end
end
