# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdSettingsMyAvatarPutRequestOneOf do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :prostore_file_id
  ]

  @type t :: %__MODULE__{
          :prostore_file_id => integer() | nil
        }

  def decode(value) do
    value
  end
end
