# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdRecycleBinActionPlansPlanItemsGet200ResponseInner do
  @moduledoc """
  Recycled Action Plan Item (Show)
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :plan_item_assignees,
    :created_at,
    :deleted_at,
    :description,
    :due_at,
    :holding_type,
    :is_blocked,
    :is_blocking,
    :plan_id,
    :position,
    :plan_section_id,
    :status,
    :title,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :plan_item_assignees =>
            [
              Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInner.t()
            ]
            | nil,
          :created_at => DateTime.t() | nil,
          :deleted_at => DateTime.t() | nil,
          :description => String.t() | nil,
          :due_at => DateTime.t() | nil,
          :holding_type => String.t() | nil,
          :is_blocked => boolean() | nil,
          :is_blocking => boolean() | nil,
          :plan_id => integer() | nil,
          :position => integer() | nil,
          :plan_section_id => integer() | nil,
          :status =>
            Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerStatus.t()
            | nil,
          :title => String.t() | nil,
          :updated_at => DateTime.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :plan_item_assignees,
      :list,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInner
    )
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(:deleted_at, :datetime, nil)
    |> Deserializer.deserialize(:due_at, :datetime, nil)
    |> Deserializer.deserialize(
      :status,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerStatus
    )
    |> Deserializer.deserialize(:updated_at, :datetime, nil)
  end
end
