# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdEquipmentLogsPostRequest1EquipmentLog do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :date,
    :datetime,
    :hours_idle,
    :hours_operating,
    :inspected,
    :inspection_hour,
    :inspection_minute,
    :notes,
    :location_id,
    :mt_location,
    :cost_code_id,
    :equipment_id,
    :equipment_name,
    :"custom_field_%{custom_field_definition_id}"
  ]

  @type t :: %__MODULE__{
          :date => Date.t() | nil,
          :datetime => DateTime.t() | nil,
          :hours_idle => integer() | nil,
          :hours_operating => integer() | nil,
          :inspected => boolean() | nil,
          :inspection_hour => integer(),
          :inspection_minute => integer(),
          :notes => String.t() | nil,
          :location_id => integer() | nil,
          :mt_location => [String.t()] | nil,
          :cost_code_id => integer() | nil,
          :equipment_id => integer() | nil,
          :equipment_name => String.t() | nil,
          :"custom_field_%{custom_field_definition_id}" =>
            Procore.Model.WorkOrderContractCustomFieldCustomFieldDefinitionId.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:date, :date, nil)
    |> Deserializer.deserialize(:datetime, :datetime, nil)
    |> Deserializer.deserialize(
      :"custom_field_%{custom_field_definition_id}",
      :struct,
      Procore.Model.WorkOrderContractCustomFieldCustomFieldDefinitionId
    )
  end
end
