# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WebhooksHooksHookIdTriggersBulkDeleteRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :company_id,
    :triggers,
    :project_id
  ]

  @type t :: %__MODULE__{
          :company_id => integer(),
          :triggers => [integer()],
          :project_id => integer()
        }

  def decode(value) do
    value
  end
end
