# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdManagedEquipmentModelsPostRequestManagedEquipmentModel do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :managed_equipment_make_id,
    :managed_equipment_type_id,
    :is_active
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :managed_equipment_make_id => integer(),
          :managed_equipment_type_id => integer(),
          :is_active => boolean() | nil
        }

  def decode(value) do
    value
  end
end
