# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdConciergePatchRequestConcierge do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :estimated_initial_projects,
    :estimated_initial_users
  ]

  @type t :: %__MODULE__{
          :estimated_initial_projects => integer() | nil,
          :estimated_initial_users => integer() | nil
        }

  def decode(value) do
    value
  end
end
