# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdDailyLogsBulkUpdatesBulkUpdatePatch200ResponseInnerAccidentLogInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :status,
    :success,
    :error
  ]

  @type t :: %__MODULE__{
          :id => integer(),
          :status => String.t(),
          :success => boolean(),
          :error => String.t() | nil
        }

  def decode(value) do
    value
  end
end
