# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11ProjectsProjectIdBidPackagesBidPackageIdBidsIdPatchRequestBid do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :lump_sum_amount,
    :bidder_comments,
    :bidder_inclusion,
    :bidder_exclusion,
    :bid_status,
    :is_bidder_committed,
    :submitted,
    :prostore_file_ids,
    :recipient_ids,
    :bid_items,
    :bid_items_to_delete
  ]

  @type t :: %__MODULE__{
          :lump_sum_amount => float() | nil,
          :bidder_comments => String.t() | nil,
          :bidder_inclusion => String.t() | nil,
          :bidder_exclusion => String.t() | nil,
          :bid_status => String.t() | nil,
          :is_bidder_committed => boolean() | nil,
          :submitted => boolean() | nil,
          :prostore_file_ids => [integer()] | nil,
          :recipient_ids => [integer()] | nil,
          :bid_items =>
            [
              Procore.Model.RestV11ProjectsProjectIdBidPackagesBidPackageIdBidsIdPatchRequestBidBidItemsInner.t()
            ]
            | nil,
          :bid_items_to_delete => [integer()] | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :bid_items,
      :list,
      Procore.Model.RestV11ProjectsProjectIdBidPackagesBidPackageIdBidsIdPatchRequestBidBidItemsInner
    )
  end
end
