# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV20CompaniesCompanyIdUsersBulkRemoveProjectDetailsPatch200ResponseDataInnerEntitiesInnerProjectsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :projectId,
    :message
  ]

  @type t :: %__MODULE__{
          :projectId => String.t() | nil,
          :message => String.t() | nil
        }

  def decode(value) do
    value
  end
end
