# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV20CompaniesCompanyIdAsyncOperationsGet200ResponseDataInner do
  @moduledoc """
  Operation details
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :operation_type,
    :started_at,
    :completed_at,
    :status,
    :error,
    :result,
    :context
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :operation_type => String.t() | nil,
          :started_at => DateTime.t() | nil,
          :completed_at => DateTime.t() | nil,
          :status => String.t() | nil,
          :error =>
            Procore.Model.RestV20CompaniesCompanyIdAsyncOperationsGet200ResponseDataInnerError.t()
            | nil,
          :result => map() | nil,
          :context => map() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:started_at, :datetime, nil)
    |> Deserializer.deserialize(:completed_at, :datetime, nil)
    |> Deserializer.deserialize(
      :error,
      :struct,
      Procore.Model.RestV20CompaniesCompanyIdAsyncOperationsGet200ResponseDataInnerError
    )
  end
end
