# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10SubmittalLogsGet200ResponseInnerResponsesInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :response
  ]

  @type t :: %__MODULE__{
          :response => String.t() | nil
        }

  def decode(value) do
    value
  end
end
