# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet400Response do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :workflowed_object_type,
    :workflowed_object_id
  ]

  @type t :: %__MODULE__{
          :workflowed_object_type => String.t() | nil,
          :workflowed_object_id => String.t() | nil
        }

  def decode(value) do
    value
  end
end
