# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10VendorsGet200ResponseInnerAllOfBiddingDistributionInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :company_name,
    :id,
    :login,
    :name
  ]

  @type t :: %__MODULE__{
          :company_name => String.t() | nil,
          :id => integer() | nil,
          :login => String.t() | nil,
          :name => String.t() | nil
        }

  def decode(value) do
    value
  end
end
