# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdBidPackagesPost201ResponseManager do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :login_information_id,
    :contact_id,
    :name,
    :email,
    :job_title,
    :invited,
    :vendor
  ]

  @type t :: %__MODULE__{
          :login_information_id => integer() | nil,
          :contact_id => integer() | nil,
          :name => String.t() | nil,
          :email => String.t() | nil,
          :job_title => String.t() | nil,
          :invited => boolean() | nil,
          :vendor =>
            Procore.Model.RestV10ProjectsProjectIdBidPackagesPost201ResponseManagerVendor.t()
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :vendor,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdBidPackagesPost201ResponseManagerVendor
    )
  end
end
