# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTestRecordsPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :plan_test_record
  ]

  @type t :: %__MODULE__{
          :plan_test_record =>
            Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTestRecordsPostRequestPlanTestRecord.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :plan_test_record,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTestRecordsPostRequestPlanTestRecord
    )
  end
end
