# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11ProjectsProjectIdScheduleLookaheadsIdGet200ResponseLookaheadTasksInnerTask do
  @moduledoc """
  The Master Scheduled Task this Lookahead Task corresponds with, if one exists
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :finish,
    :start
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :finish => DateTime.t() | nil,
          :start => DateTime.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:finish, :datetime, nil)
    |> Deserializer.deserialize(:start, :datetime, nil)
  end
end
