# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkforcePlanningV2CompaniesCompanyIdJobTitlesPostRequest do
  @moduledoc """
  Request body schema for creating a new Job Title.
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :group_ids,
    :globally_accessible,
    :color,
    :type,
    :hourly_rate
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :group_ids => [String.t()],
          :globally_accessible => boolean(),
          :color => String.t() | nil,
          :type => String.t() | nil,
          :hourly_rate => float() | nil
        }

  def decode(value) do
    value
  end
end
