# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkflowInstancesGet200ResponseInnerCurrentWorkflowActivitiesInnerPerformActivityData do
  @moduledoc """
  JSON to be submitted as the request body
  """

  @derive Jason.Encoder
  defstruct [
    :workflow_activity_history
  ]

  @type t :: %__MODULE__{
          :workflow_activity_history =>
            Procore.Model.RestV10WorkflowInstancesGet200ResponseInnerCurrentWorkflowActivitiesInnerPerformActivityDataWorkflowActivityHistory.t()
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :workflow_activity_history,
      :struct,
      Procore.Model.RestV10WorkflowInstancesGet200ResponseInnerCurrentWorkflowActivitiesInnerPerformActivityDataWorkflowActivityHistory
    )
  end
end
