# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdScheduleLookaheadTasksPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :lookahead_task
  ]

  @type t :: %__MODULE__{
          :lookahead_task => Procore.Model.LookaheadTask.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:lookahead_task, :struct, Procore.Model.LookaheadTask)
  end
end
