# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV20CompaniesCompanyIdProjectsProjectIdWorkflowsInstancesIdGet200ResponseDataCurrentStepOccurrenceResponseOccurrencesInnerAssignee do
  @moduledoc """
  Details of the response assignee
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :login,
    :name,
    :company,
    :required
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :login => String.t() | nil,
          :name => String.t() | nil,
          :company =>
            Procore.Model.RestV20CompaniesCompanyIdProjectsProjectIdWorkflowsInstancesIdGet200ResponseDataCurrentStepOccurrenceResponseOccurrencesInnerAssigneeCompany.t()
            | nil,
          :required => boolean() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :company,
      :struct,
      Procore.Model.RestV20CompaniesCompanyIdProjectsProjectIdWorkflowsInstancesIdGet200ResponseDataCurrentStepOccurrenceResponseOccurrencesInnerAssigneeCompany
    )
  end
end
