# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerAllOfCurrencyConfiguration do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :base_currency_iso_code,
    :currency_iso_code,
    :currency_exchange_rate
  ]

  @type t :: %__MODULE__{
          :base_currency_iso_code => String.t() | nil,
          :currency_iso_code => String.t() | nil,
          :currency_exchange_rate => String.t() | nil
        }

  def decode(value) do
    value
  end
end
