# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTemplateReferencesGet200ResponseInnerPayload do
  @moduledoc """
  Contains specific attributes depending on the type of Reference
  """

  @derive Jason.Encoder
  defstruct [
    :attachment,
    :drawing_id,
    :drawing_revision_id,
    :file_version_id,
    :folder_id,
    :specification_section_id,
    :specification_section_current_revision_id,
    :generic_tool_item_id,
    :form_id,
    :meeting_id,
    :observation_item_id
  ]

  @type t :: %__MODULE__{
          :attachment =>
            Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTemplateReferencesGet200ResponseInnerPayloadAttachment.t()
            | nil,
          :drawing_id => integer() | nil,
          :drawing_revision_id => integer() | nil,
          :file_version_id => integer() | nil,
          :folder_id => integer() | nil,
          :specification_section_id => integer() | nil,
          :specification_section_current_revision_id => integer() | nil,
          :generic_tool_item_id => integer() | nil,
          :form_id => integer() | nil,
          :meeting_id => integer() | nil,
          :observation_item_id => integer() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :attachment,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTemplateReferencesGet200ResponseInnerPayloadAttachment
    )
  end
end
