# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10BudgetViewSnapshotsPost202ResponseData do
  @moduledoc """
  Budget View Snapshot Request
  """

  @derive Jason.Encoder
  defstruct [
    :snapshot_request_id,
    :status,
    :budget_template_id,
    :project_id,
    :company_id
  ]

  @type t :: %__MODULE__{
          :snapshot_request_id => integer() | nil,
          :status => String.t() | nil,
          :budget_template_id => integer() | nil,
          :project_id => integer() | nil,
          :company_id => integer() | nil
        }

  def decode(value) do
    value
  end
end
