# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdManagedEquipmentLogsPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :managed_equipment_log
  ]

  @type t :: %__MODULE__{
          :managed_equipment_log =>
            Procore.Model.RestV10CompaniesCompanyIdManagedEquipmentLogsPostRequestManagedEquipmentLog.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :managed_equipment_log,
      :struct,
      Procore.Model.RestV10CompaniesCompanyIdManagedEquipmentLogsPostRequestManagedEquipmentLog
    )
  end
end
