# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :plan_template_item_assignee
  ]

  @type t :: %__MODULE__{
          :plan_template_item_assignee =>
            Procore.Model.RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesPostRequestPlanTemplateItemAssignee.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :plan_template_item_assignee,
      :struct,
      Procore.Model.RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesPostRequestPlanTemplateItemAssignee
    )
  end
end
