# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WebhooksHooksHookIdTriggersBulkPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :company_id,
    :api_version,
    :triggers,
    :project_id
  ]

  @type t :: %__MODULE__{
          :company_id => integer(),
          :api_version => String.t(),
          :triggers => [Procore.Model.CompanyTriggerTrigger.t()],
          :project_id => integer()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:triggers, :list, Procore.Model.CompanyTriggerTrigger)
  end
end
