# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdBudgetModificationsGet200ResponseInner do
  @moduledoc """
  Budget Modification
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :created_at,
    :from_budget_line_item_id,
    :notes,
    :origin_data,
    :origin_id,
    :to_budget_line_item_id,
    :transfer_amount,
    :updated_at
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :created_at => DateTime.t() | nil,
          :from_budget_line_item_id => integer() | nil,
          :notes => String.t() | nil,
          :origin_data => String.t() | nil,
          :origin_id => String.t() | nil,
          :to_budget_line_item_id => integer() | nil,
          :transfer_amount => String.t() | nil,
          :updated_at => DateTime.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(:updated_at, :datetime, nil)
  end
end
