# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkforcePlanningV2CompaniesCompanyIdGroupsGroupIdTagsGet200ResponseInner do
  @moduledoc """
  Response schema for a single Tag.
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :name,
    :group_ids,
    :globally_accessible,
    :abbreviation,
    :require_expr_date,
    :expr_days_warning,
    :color,
    :categories
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :group_ids => [String.t()] | nil,
          :globally_accessible => boolean() | nil,
          :abbreviation => String.t() | nil,
          :require_expr_date => boolean() | nil,
          :expr_days_warning => integer() | nil,
          :color => String.t() | nil,
          :categories => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
