# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11ProjectsProjectIdScheduleLookaheadsIdGet200Response do
  @moduledoc """
  Schedule Lookahead
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :start_date,
    :end_date,
    :created_at,
    :data_date,
    :created_by,
    :label,
    :lookahead_tasks,
    :generation_errors,
    :status,
    :weeks
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :start_date => Date.t() | nil,
          :end_date => Date.t() | nil,
          :created_at => DateTime.t() | nil,
          :data_date => DateTime.t() | nil,
          :created_by =>
            Procore.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.t() | nil,
          :label => String.t() | nil,
          :lookahead_tasks =>
            [
              Procore.Model.RestV11ProjectsProjectIdScheduleLookaheadsIdGet200ResponseLookaheadTasksInner.t()
            ]
            | nil,
          :generation_errors =>
            [
              Procore.Model.RestV11ProjectsProjectIdScheduleLookaheadsIdGet200ResponseGenerationErrorsInner.t()
            ]
            | nil,
          :status => String.t() | nil,
          :weeks => integer() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:start_date, :date, nil)
    |> Deserializer.deserialize(:end_date, :date, nil)
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(:data_date, :datetime, nil)
    |> Deserializer.deserialize(
      :created_by,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy
    )
    |> Deserializer.deserialize(
      :lookahead_tasks,
      :list,
      Procore.Model.RestV11ProjectsProjectIdScheduleLookaheadsIdGet200ResponseLookaheadTasksInner
    )
    |> Deserializer.deserialize(
      :generation_errors,
      :list,
      Procore.Model.RestV11ProjectsProjectIdScheduleLookaheadsIdGet200ResponseGenerationErrorsInner
    )
  end
end
