# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV20CompaniesCompanyIdWorkflowsTemplatesGet200ResponseDataInnerVersionsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :version
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :version => String.t() | nil
        }

  def decode(value) do
    value
  end
end
