# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10BimModelsGet200ResponseInnerOneOf1CurrentRevisionMinBoundary do
  @moduledoc """
  3D Coordinate Point
  """

  @derive Jason.Encoder
  defstruct [
    :x,
    :y,
    :z
  ]

  @type t :: %__MODULE__{
          :x => String.t() | nil,
          :y => String.t() | nil,
          :z => String.t() | nil
        }

  def decode(value) do
    value
  end
end
