# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11RequisitionsGet200ResponseInnerItemsInnerWbsCodeSegmentItemsInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :code,
    :name,
    :path_ids,
    :path_codes,
    :segment_type,
    :segment_id
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :code => String.t() | nil,
          :name => String.t() | nil,
          :path_ids => [integer()] | nil,
          :path_codes => [String.t()] | nil,
          :segment_type => String.t() | nil,
          :segment_id => integer() | nil
        }

  def decode(value) do
    value
  end
end
