# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdIncidentsInjuryFilingTypesIdPatchRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :filing_type
  ]

  @type t :: %__MODULE__{
          :filing_type =>
            Procore.Model.RestV10CompaniesCompanyIdIncidentsInjuryFilingTypesIdPatchRequestFilingType.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :filing_type,
      :struct,
      Procore.Model.RestV10CompaniesCompanyIdIncidentsInjuryFilingTypesIdPatchRequestFilingType
    )
  end
end
