# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10RequisitionsRequisitionIdWholeChangeOrderItemsIdPatch200Response do
  @moduledoc """
  Requisition (Subcontractor Invoice) Whole Change Order Item
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :cost_code_id,
    :item_type,
    :line_item_id,
    :description_of_work,
    :scheduled_value,
    :work_completed_from_previous_application,
    :work_completed_this_period,
    :materials_presently_stored,
    :total_completed_and_stored_to_date,
    :total_completed_and_stored_to_date_percent,
    :work_completed_retainage_from_previous_application,
    :work_completed_retainage_retained_this_period,
    :work_completed_retainage_percent_this_period,
    :ssr_manual_override,
    :materials_stored_retainage_currently_retained,
    :materials_stored_retainage_percent_this_period,
    :work_completed_retainage_released_this_period,
    :materials_stored_retainage_released_this_period,
    :scheduled_quantity,
    :scheduled_unit_price,
    :work_completed_this_period_quantity,
    :work_completed_from_previous_application_quantity,
    :change_order_package_id,
    :subcontractor_claimed_amount,
    :comment,
    :status,
    :wbs_code,
    :position,
    :currency_configuration,
    :materials_moved,
    :materials_retainage_retained_moved
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :cost_code_id => integer() | nil,
          :item_type => String.t() | nil,
          :line_item_id => integer() | nil,
          :description_of_work => String.t() | nil,
          :scheduled_value => String.t() | nil,
          :work_completed_from_previous_application => String.t() | nil,
          :work_completed_this_period => String.t() | nil,
          :materials_presently_stored => String.t() | nil,
          :total_completed_and_stored_to_date => String.t() | nil,
          :total_completed_and_stored_to_date_percent => String.t() | nil,
          :work_completed_retainage_from_previous_application => String.t() | nil,
          :work_completed_retainage_retained_this_period => String.t() | nil,
          :work_completed_retainage_percent_this_period => String.t() | nil,
          :ssr_manual_override => boolean() | nil,
          :materials_stored_retainage_currently_retained => String.t() | nil,
          :materials_stored_retainage_percent_this_period => String.t() | nil,
          :work_completed_retainage_released_this_period => String.t() | nil,
          :materials_stored_retainage_released_this_period => String.t() | nil,
          :scheduled_quantity => String.t() | nil,
          :scheduled_unit_price => String.t() | nil,
          :work_completed_this_period_quantity => String.t() | nil,
          :work_completed_from_previous_application_quantity => String.t() | nil,
          :change_order_package_id => integer() | nil,
          :subcontractor_claimed_amount => String.t() | nil,
          :comment => String.t() | nil,
          :status => String.t() | nil,
          :wbs_code =>
            Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerWbsCode.t() | nil,
          :position => integer() | nil,
          :currency_configuration =>
            Procore.Model.RestV10RequisitionsRequisitionIdAddChangeOrderPackagePost201ResponseInnerCurrencyConfiguration.t()
            | nil,
          :materials_moved => String.t() | nil,
          :materials_retainage_retained_moved => String.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :wbs_code,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInnerWbsCode
    )
    |> Deserializer.deserialize(
      :currency_configuration,
      :struct,
      Procore.Model.RestV10RequisitionsRequisitionIdAddChangeOrderPackagePost201ResponseInnerCurrencyConfiguration
    )
  end
end
