# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdAppConfigurationsPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :applies_to_all_projects,
    :applies_to_company,
    :app_installation_id,
    :company_id,
    :instance_configuration,
    :project_ids,
    :title
  ]

  @type t :: %__MODULE__{
          :applies_to_all_projects => boolean() | nil,
          :applies_to_company => boolean() | nil,
          :app_installation_id => integer(),
          :company_id => integer(),
          :instance_configuration => map(),
          :project_ids => [integer()] | nil,
          :title => String.t()
        }

  def decode(value) do
    value
  end
end
