# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV20CompaniesCompanyIdUsersBulkUpdateProjectDetailsPatch200ResponseDataInner do
  @moduledoc """
  entities with successes
  """

  @derive Jason.Encoder
  defstruct [
    :entities
  ]

  @type t :: %__MODULE__{
          :entities =>
            [
              Procore.Model.RestV20CompaniesCompanyIdUsersBulkUpdateProjectDetailsPatch200ResponseDataInnerEntitiesInner.t()
            ]
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :entities,
      :list,
      Procore.Model.RestV20CompaniesCompanyIdUsersBulkUpdateProjectDetailsPatch200ResponseDataInnerEntitiesInner
    )
  end
end
