# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ChangeOrderPackagesPost201ResponseLineItemsInnerMarkupLineItemsInnerMarkupDestinationCostCode do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :origin_id,
    :origin_data
  ]

  @type t :: %__MODULE__{
          :origin_id => String.t() | nil,
          :origin_data => String.t() | nil
        }

  def decode(value) do
    value
  end
end
