# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdActionPlansPlanReferencesPostRequest1PlanReferencePayload do
  @moduledoc """
  One of attachment, drawing_revision_id, file_version_id, specification_section_id, submittal_log_id, generic_tool_item_id, form_id, meeting_id, or observation_item_id is accepted depending on the type provided
  """

  @derive Jason.Encoder
  defstruct [
    :drawing_revision_id,
    :file_version_id,
    :specification_section_id,
    :submittal_log_id,
    :attachment,
    :generic_tool_item_id,
    :form_id,
    :meeting_id,
    :observation_item_id
  ]

  @type t :: %__MODULE__{
          :drawing_revision_id => integer() | nil,
          :file_version_id => integer() | nil,
          :specification_section_id => integer() | nil,
          :submittal_log_id => integer() | nil,
          :attachment => String.t() | nil,
          :generic_tool_item_id => integer() | nil,
          :form_id => integer() | nil,
          :meeting_id => integer() | nil,
          :observation_item_id => integer() | nil
        }

  def decode(value) do
    value
  end
end
