# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :configurable_field_set
  ]

  @type t :: %__MODULE__{
          :configurable_field_set =>
            Procore.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequestConfigurableFieldSet.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :configurable_field_set,
      :struct,
      Procore.Model.RestV10CompaniesCompanyIdConfigurableFieldSetsPostRequestConfigurableFieldSet
    )
  end
end
