# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkforcePlanningV2CompaniesCompanyIdProjectsPostRequestCategoriesInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :subcategories
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :subcategories =>
            [
              Procore.Model.RestV10WorkforcePlanningV2CompaniesCompanyIdProjectsGet200ResponseInnerCategoriesInnerSubcategoriesInner.t()
            ]
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :subcategories,
      :list,
      Procore.Model.RestV10WorkforcePlanningV2CompaniesCompanyIdProjectsGet200ResponseInnerCategoriesInnerSubcategoriesInner
    )
  end
end
