# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdActionPlansPlanReferencesPostRequestPlanReference do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :plan_item_id,
    :type,
    :payload
  ]

  @type t :: %__MODULE__{
          :plan_item_id => integer(),
          :type => String.t(),
          :payload => Procore.Model.ActionPlanTemplateReferencesInner1Payload.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :payload,
      :struct,
      Procore.Model.ActionPlanTemplateReferencesInner1Payload
    )
  end
end
