# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemAssigneesGet200ResponseInner do
  @moduledoc """
  Action Plan Item Assignee (Show)
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :plan_item_id,
    :created_at,
    :is_holding,
    :is_locked,
    :party,
    :plan_id,
    :role,
    :role_id,
    :signature,
    :updated_at,
    :verification_method,
    :plan_template_item_id,
    :plan_template_id
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :plan_item_id => integer() | nil,
          :created_at => String.t() | nil,
          :is_holding => boolean() | nil,
          :is_locked => boolean() | nil,
          :party =>
            Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInnerManager.t()
            | nil,
          :plan_id => integer() | nil,
          :role => String.t() | nil,
          :role_id => integer() | nil,
          :signature =>
            Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInnerSignature.t()
            | nil,
          :updated_at => String.t() | nil,
          :verification_method =>
            Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInnerVerificationMethod.t()
            | nil,
          :plan_template_item_id => integer() | nil,
          :plan_template_id => integer() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :party,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInnerManager
    )
    |> Deserializer.deserialize(
      :signature,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInnerSignature
    )
    |> Deserializer.deserialize(
      :verification_method,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInnerVerificationMethod
    )
  end
end
