# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11ProjectsProjectIdFormsGet200ResponseInnerFillablePdf do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :url,
    :filename,
    :name
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :url => String.t() | nil,
          :filename => String.t() | nil,
          :name => String.t() | nil
        }

  def decode(value) do
    value
  end
end
