# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11ProjectsProjectIdMeetingTopicsMeetingTopicIdParentMinutesGet200ResponseInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :meeting_id,
    :created_on,
    :minutes,
    :no_minutes,
    :marked
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :meeting_id => integer() | nil,
          :created_on => Date.t() | nil,
          :minutes => String.t() | nil,
          :no_minutes => boolean() | nil,
          :marked => boolean() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:created_on, :date, nil)
  end
end
