# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdIncidentsActionTypesBulkUpdatePatchRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :action_type
  ]

  @type t :: %__MODULE__{
          :action_type =>
            Procore.Model.RestV10CompaniesCompanyIdIncidentsActionTypesBulkUpdatePatchRequestActionType.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :action_type,
      :struct,
      Procore.Model.RestV10CompaniesCompanyIdIncidentsActionTypesBulkUpdatePatchRequestActionType
    )
  end
end
