# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10ProjectsProjectIdPlanRevisionLogsPostRequest do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :plan_revision_log
  ]

  @type t :: %__MODULE__{
          :plan_revision_log =>
            Procore.Model.RestV10ProjectsProjectIdPlanRevisionLogsPostRequestPlanRevisionLog.t()
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :plan_revision_log,
      :struct,
      Procore.Model.RestV10ProjectsProjectIdPlanRevisionLogsPostRequestPlanRevisionLog
    )
  end
end
