# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkforcePlanningV2CompaniesCompanyIdTagsTagIdGroupsPost200ResponseInner do
  @moduledoc """
  Response schema containing a list of Group IDs.
  """

  @derive Jason.Encoder
  defstruct [
    :group_ids
  ]

  @type t :: %__MODULE__{
          :group_ids => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
