# NOTE: This file is auto generated by OpenAPI Generator 7.12.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WebhooksHooksHookIdTriggersBulkDelete207ResponseFailedInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :code,
    :trigger
  ]

  @type t :: %__MODULE__{
          :code => String.t() | nil,
          :trigger => integer() | nil
        }

  def decode(value) do
    value
  end
end
