# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CompaniesCompanyIdIncidentsWorkActivitiesPostRequestWorkActivity do
  @moduledoc """
  Work Activity object
  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :active
  ]

  @type t :: %__MODULE__{
          :name => String.t(),
          :active => boolean() | nil
        }

  def decode(value) do
    value
  end
end
