# NOTE: This file is auto generated by OpenAPI Generator 7.7.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV13CompaniesCompanyIdUsersBulkAddPost207Response do
  @moduledoc """
  entities with successes
  """

  @derive Jason.Encoder
  defstruct [
    :entities,
    :errors
  ]

  @type t :: %__MODULE__{
          :entities => [%{optional(String.t()) => any()}] | nil,
          :errors => [%{optional(String.t()) => any()}] | nil
        }

  def decode(value) do
    value
  end
end
