# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV11ProjectsProjectIdVendorsGet200ResponseInnerOneOf2 do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :logo,
    :is_active,
    :id,
    :name
  ]

  @type t :: %__MODULE__{
          :logo => String.t() | nil,
          :is_active => boolean() | nil,
          :id => integer() | nil,
          :name => String.t() | nil
        }

  def decode(value) do
    value
  end
end
