# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10CoordinationIssuesGet200ResponseInnerAllOfDrawingMarkupPreviewImagesInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :drawing_revision_id,
    :name,
    :content_type,
    :url
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :drawing_revision_id => integer() | nil,
          :name => String.t() | nil,
          :content_type => String.t() | nil,
          :url => String.t() | nil
        }

  def decode(value) do
    value
  end
end
