# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.RestV10WorkOrderContractsPost201Response do
  @moduledoc """
  Work Order Contract
  """

  @derive Jason.Encoder
  defstruct [
    :accounting_method,
    :actual_completion_date,
    :approval_letter_date,
    :approved_change_orders,
    :attachments,
    :change_order_packages,
    :change_order_requests,
    :contract_date,
    :contract_start_date,
    :contract_estimated_completion_date,
    :created_at,
    :created_by_id,
    :deleted_at,
    :description,
    :draft_change_orders_amount,
    :exclusions,
    :executed,
    :execution_date,
    :grand_total,
    :id,
    :inclusions,
    :invoice_contacts,
    :issued_on_date,
    :letter_of_intent_date,
    :line_items,
    :number,
    :origin_data,
    :origin_code,
    :origin_id,
    :payments_issued,
    :pending_change_orders,
    :pending_revised_contract,
    :percentage_paid,
    :potential_change_orders,
    :private,
    :project,
    :remaining_balance_outstanding,
    :requisitions_are_enabled,
    :retainage_percent,
    :returned_date,
    :revised_contract,
    :signed_contract_received_date,
    :show_line_items_to_non_admins,
    :status,
    :title,
    :total_draw_requests_amount,
    :total_payments,
    :total_requisitions_amount,
    :updated_at,
    :vendor,
    :currency_configuration
  ]

  @type t :: %__MODULE__{
          :accounting_method => String.t() | nil,
          :actual_completion_date => Date.t() | nil,
          :approval_letter_date => String.t() | nil,
          :approved_change_orders => String.t() | nil,
          :attachments =>
            [Procore.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner.t()] | nil,
          :change_order_packages =>
            [Procore.Model.RestV10WorkOrderContractsPost201ResponseChangeOrderPackagesInner.t()]
            | nil,
          :change_order_requests =>
            [
              [
                Procore.Model.RestV10WorkOrderContractsPost201ResponseChangeOrderRequestsInnerInner.t()
              ]
            ]
            | nil,
          :contract_date => Date.t() | nil,
          :contract_start_date => Date.t() | nil,
          :contract_estimated_completion_date => Date.t() | nil,
          :created_at => DateTime.t() | nil,
          :created_by_id => integer() | nil,
          :deleted_at => DateTime.t() | nil,
          :description => String.t() | nil,
          :draft_change_orders_amount => String.t() | nil,
          :exclusions => String.t() | nil,
          :executed => boolean() | nil,
          :execution_date => Date.t() | nil,
          :grand_total => String.t() | nil,
          :id => integer() | nil,
          :inclusions => String.t() | nil,
          :invoice_contacts =>
            [Procore.Model.RestV10WorkOrderContractsPost201ResponseInvoiceContactsInner.t()] | nil,
          :issued_on_date => Date.t() | nil,
          :letter_of_intent_date => Date.t() | nil,
          :line_items =>
            [Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInner.t()] | nil,
          :number => String.t() | nil,
          :origin_data => String.t() | nil,
          :origin_code => String.t() | nil,
          :origin_id => String.t() | nil,
          :payments_issued =>
            [Procore.Model.RestV10WorkOrderContractsPost201ResponsePaymentsIssuedInner.t()] | nil,
          :pending_change_orders => String.t() | nil,
          :pending_revised_contract => String.t() | nil,
          :percentage_paid => String.t() | nil,
          :potential_change_orders =>
            [Procore.Model.RestV10WorkOrderContractsPost201ResponsePotentialChangeOrdersInner.t()]
            | nil,
          :private => boolean() | nil,
          :project => Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerProject.t() | nil,
          :remaining_balance_outstanding => String.t() | nil,
          :requisitions_are_enabled => boolean() | nil,
          :retainage_percent => String.t() | nil,
          :returned_date => Date.t() | nil,
          :revised_contract => String.t() | nil,
          :signed_contract_received_date => Date.t() | nil,
          :show_line_items_to_non_admins => boolean() | nil,
          :status => String.t() | nil,
          :title => String.t() | nil,
          :total_draw_requests_amount => String.t() | nil,
          :total_payments => String.t() | nil,
          :total_requisitions_amount => String.t() | nil,
          :updated_at => DateTime.t() | nil,
          :vendor => Procore.Model.RestV10WorkOrderContractsPost201ResponseVendor.t() | nil,
          :currency_configuration =>
            Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration.t()
            | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:actual_completion_date, :date, nil)
    |> Deserializer.deserialize(
      :attachments,
      :list,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseAttachmentsInner
    )
    |> Deserializer.deserialize(
      :change_order_packages,
      :list,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseChangeOrderPackagesInner
    )
    |> Deserializer.deserialize(:contract_date, :date, nil)
    |> Deserializer.deserialize(:contract_start_date, :date, nil)
    |> Deserializer.deserialize(:contract_estimated_completion_date, :date, nil)
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(:deleted_at, :datetime, nil)
    |> Deserializer.deserialize(:execution_date, :date, nil)
    |> Deserializer.deserialize(
      :invoice_contacts,
      :list,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseInvoiceContactsInner
    )
    |> Deserializer.deserialize(:issued_on_date, :date, nil)
    |> Deserializer.deserialize(:letter_of_intent_date, :date, nil)
    |> Deserializer.deserialize(
      :line_items,
      :list,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseLineItemsInner
    )
    |> Deserializer.deserialize(
      :payments_issued,
      :list,
      Procore.Model.RestV10WorkOrderContractsPost201ResponsePaymentsIssuedInner
    )
    |> Deserializer.deserialize(
      :potential_change_orders,
      :list,
      Procore.Model.RestV10WorkOrderContractsPost201ResponsePotentialChangeOrdersInner
    )
    |> Deserializer.deserialize(
      :project,
      :struct,
      Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerProject
    )
    |> Deserializer.deserialize(:returned_date, :date, nil)
    |> Deserializer.deserialize(:signed_contract_received_date, :date, nil)
    |> Deserializer.deserialize(:updated_at, :datetime, nil)
    |> Deserializer.deserialize(
      :vendor,
      :struct,
      Procore.Model.RestV10WorkOrderContractsPost201ResponseVendor
    )
    |> Deserializer.deserialize(
      :currency_configuration,
      :struct,
      Procore.Model.RestV10WorkOrderContractsGet200ResponseInnerCurrencyConfiguration
    )
  end
end
