# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.ScheduleType1 do
  @moduledoc """
  Schedule Type object
  """

  @derive Jason.Encoder
  defstruct [
    :key,
    :p6_id
  ]

  @type t :: %__MODULE__{
          :key => String.t(),
          :p6_id => String.t() | nil
        }

  def decode(value) do
    value
  end
end
