# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.StandardCostCodeSyncBodyUpdatesInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :name,
    :id,
    :code,
    :parent_id,
    :origin_id,
    :origin_data
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :id => integer() | nil,
          :code => String.t() | nil,
          :parent_id => integer() | nil,
          :origin_id => String.t() | nil,
          :origin_data => String.t() | nil
        }

  def decode(value) do
    value
  end
end
