# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.TimeAndMaterialEquipmentLogBulkUpdateBody do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :time_and_material_equipment_logs
  ]

  @type t :: %__MODULE__{
          :time_and_material_equipment_logs => [
            Procore.Model.TimeAndMaterialEquipmentLogProperties.t()
          ]
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(
      :time_and_material_equipment_logs,
      :list,
      Procore.Model.TimeAndMaterialEquipmentLogProperties
    )
  end
end
