# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.TimecardEntry3ClockIn do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil
        }

  def decode(value) do
    value
  end
end
