# NOTE: This file is auto generated by OpenAPI Generator 7.8.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.VendorComment do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :body,
    :created_at,
    :rating,
    :attachments,
    :created_by
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :body => String.t() | nil,
          :created_at => DateTime.t() | nil,
          :rating => integer() | nil,
          :attachments => [Procore.Model.VendorCommentAttachmentsInner.t()] | nil,
          :created_by => Procore.Model.VendorCommentCreatedBy.t() | nil
        }

  alias Procore.Deserializer

  def decode(value) do
    value
    |> Deserializer.deserialize(:created_at, :datetime, nil)
    |> Deserializer.deserialize(:attachments, :list, Procore.Model.VendorCommentAttachmentsInner)
    |> Deserializer.deserialize(:created_by, :struct, Procore.Model.VendorCommentCreatedBy)
  end
end
