# NOTE: This file is auto generated by OpenAPI Generator 7.9.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Procore.Model.WorkflowActivityHistory do
  @moduledoc """
  Workflow Activity History object
  """

  @derive Jason.Encoder
  defstruct [
    :workflow_activity_id,
    :workflow_instance_id,
    :workflow_user_role_id,
    :performed_by_id,
    :comments,
    :attachments
  ]

  @type t :: %__MODULE__{
          :workflow_activity_id => integer(),
          :workflow_instance_id => integer(),
          :workflow_user_role_id => integer(),
          :performed_by_id => integer(),
          :comments => String.t() | nil,
          :attachments => [String.t()] | nil
        }

  def decode(value) do
    value
  end
end
